# Since we really don't want any of Travis' Python
language: generic
sudo: false

os:
  - linux
  - osx

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
  matrix:
    - Python=3.5
    - Python=3.6

before_install:
  # Taken from: http://conda.pydata.org/docs/travis.html
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi;
  - bash miniconda.sh -b -p $MINICONDA_DIR
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - export QT_QPA_PLATFORM="offscreen"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q pyyaml
  - conda info -a
  - sed -i -e "s/python=3/python=$Python/" environment.yml

install:
  - conda env create -q -f environment.yml
  - source activate unidata-workshop
  - python --version
  - conda list

script:
  - python run_notebooks.py
  - python notebooks/Command_Line_Tools/synopticplot.py  --gfslevel 850 --gfsfield Relative_humidity_isobaric --savefig --imgformat jpg
  - python notebooks/Command_Line_Tools/skewt.py --date 20170420 --hour 0 --station BMX  --savefig  --imgformat jpg
