language: ruby
sudo: false

rvm: 2.2

branches:
  only:
    - gh-pages
    - /(.*)/

before_install:
  - gem install github-pages;
  - pip install --user linkchecker pyopenssl ndg-httpsclient pyasn1 "requests<=2.9";

script:
  - jekyll build 2>build.log;
  - if [ -s build.log ]; then
      echo Build produced errors:;
      cat build.log;
      false;
    else
      echo Checking links;
      linkchecker --anchors --ignore mybinder --check-extern _site;
    fi;
