# Since we really don't want any of Travis' Python
language: generic
sudo: false

os:
  - linux
  - osx

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
  matrix:
    - Python=3.4
    - Python=3.5

before_install:
  # Taken from: http://conda.pydata.org/docs/travis.html
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $MINICONDA_DIR;
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - sed -i -e "s/python=3/python=$Python/" environment.yml

install:
  - conda env create -f environment.yml
  - source activate unidata-workshop
  - python --version
  - conda list

script:
  - find . -name \*.ipynb -print0 | xargs -0 -n1 jupyter nbconvert --execute --ExecutePreprocessor.timeout=180 --to=notebook --stdout >| /dev/null;
