 name: unidata-workshop
 channels:
   - https://conda.anaconda.org/conda-forge
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - owslib
   - metpy
   - pint
   - shapely
   - siphon
   - xarray
   - pip
   - pip:
     - https://github.com/Unidata/python-awips/archive/0.9.7.tar.gz

