 name: unidata-workshop
 channels:
   - https://conda.anaconda.org/conda-forge
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - owslib
   - metpy
   - pint
   - shapely
   - siphon
   - xarray
   - pip
   - pip:
     - https://testpypi.python.org/packages/9f/ac/4872c4a8ebe655345d532828ad061ccc764d43386e92604cacd4e4a9887c/python-awips-0.9.7.tar.gz

