name: workshop
channels:
  - https://conda.binstar.org/Unidata
dependencies:
  - python=3
  - ipython
  - numpy
  - netcdf4
  - matplotlib
  - cartopy
  - OWSLib
  - siphon
  - MetPy
  - xray
  - pyzmq
  - jinja2
  - tornado
  - jsonschema
  - networkx
  - anaconda-client
