 name: unidata-workshop
 channels:
   - https://conda.anaconda.org/conda-forge
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - networkx
   - netcdf4
   - owslib
   - metpy
   - pint
   - siphon
   - xarray
   - anaconda-client
   - pip
   - pip:
     - https://testpypi.python.org/packages/2d/42/7995409e0f71a7d61400809c74f05eb6cd6eaf18ce5e1940fddb2ebee58b/python-awips-0.9.5.tar.gz

