name: workshop
channels:
  - https://conda.binstar.org/scitools
  - https://conda.binstar.org/Unidata
dependencies:
  - python=3
  - numpy
  - matplotlib
  - cartopy
  - ipython-notebook
  - networkx
  - netcdf4
  - owslib
  - metpy
  - siphon
